/**
 * Every sentence the product surface renders, in one module.
 *
 * This is deliberately not an i18n framework: there is exactly one locale today and adding a translation layer
 * before there is a second language would cost more than it buys. What it does buy is that a real
 * localization pass can replace this file (or key it by locale) without touching a single component — nothing
 * below is interpolated with markup, and no component builds a sentence out of fragments. Vocabulary labels
 * (statuses, categories, tabs) live in `@suhbat/product`'s `labels.ts` because they are product vocabulary,
 * not page copy.
 */

export const ui = {
  brand: {
    name: 'SUHBAT AI',
    tagline: 'Meeting memory for companies that decide things in more than one language.',
  },
  nav: {
    home: 'Dashboard',
    meetings: 'Meetings',
    companies: 'Companies',
    projects: 'Projects',
    tasks: 'Tasks',
    knowledge: 'Knowledge',
    ask: 'Ask AI',
    settings: 'Settings',
    newMeeting: 'New meeting',
    sections: 'Sections',
    collapse: 'Collapse sidebar',
    expand: 'Expand sidebar',
    switchWorkspace: 'Switch workspace',
    searchPlaceholder: 'Search meetings, companies, people',
    account: 'Account',
    signOut: 'Sign out',
  },
  demo: {
    badge: 'Demo data',
    bannerTitle: 'Typed demo fixtures, not a connected pipeline',
    bannerBody:
      'Every screen below runs on versioned fixtures in the product package: meetings, transcripts, decisions, tasks and citations. Nothing is transcribed, analysed or stored by this build.',
    bannerProvenance: 'Data source',
    dismiss: 'Understood',
    mutations: 'Demo transitions',
    mutationsHint:
      'Advancing a processing step or ticking a task changes in-memory demo state only.',
  },
  common: {
    apply: 'Apply',
    reset: 'Reset',
    all: 'All',
    back: 'Back',
    close: 'Close',
    more: 'More',
    notAvailable: 'Not available in this build',
    retry: 'Try again',
    openInTranscript: 'Open in transcript',
    showing: 'Showing',
    of: 'of',
    lines: 'lines',
    meetings: 'meetings',
    minutes: 'min',
    participants: 'participants',
    languages: 'Languages',
    duration: 'Duration',
    captured: 'Captured',
    untitled: 'Untitled',
    noCompany: 'No company',
    viewAll: 'View all',
    none: 'None recorded',
    export: 'Export and print',
    exportNote:
      'An export is built from the records this workspace already holds. In demo mode those records are the fixtures, and the file says so in its own header.',
    share: 'Share',
    shareNote:
      'Sharing needs workspace permissions in the live product; demo fixtures have no ACL to share under.',
    copyLink: 'Copy link',
    copied: 'Copied',
    actions: 'Actions',
  },
  errors: {
    workspaceUnavailableTitle: 'Workspace unavailable',
    workspaceUnavailableBody:
      'This workspace does not exist in the current data source, or you are not a member of it. Workspace access is decided by membership, never by a URL.',
    signedOut: 'Sign in to open a workspace.',
    notFoundTitle: 'Not found in this workspace',
    providerTitle: 'Data source is not reachable',
    retryNavigation: 'Reload',
  },
  dashboard: {
    title: 'Dashboard',
    intro: 'What was captured, what was decided, and what is still owed.',
    today: 'Today',
    todayEmpty: 'No meetings captured today.',
    attention: 'Needs attention',
    attentionEmpty: 'Nothing is stuck in the pipeline.',
    openTasks: 'Open tasks',
    overdueTasks: 'Overdue',
    decisions7d: 'Decisions (7 days)',
    openQuestions: 'Open questions',
    recentMeetings: 'Recent meetings',
    recentDecisions: 'Recent decisions',
    recentTasks: 'Recent follow-ups',
    companies: 'Companies',
    processing: 'In the pipeline',
    emptyTitle: 'No meetings yet',
    emptyBody:
      'Record a meeting with the desktop recorder, or create a draft to hold a place for one.',
    emptyAction: 'New meeting',
  },
  meetings: {
    title: 'Meetings',
    intro: 'Every captured conversation, with its transcript, topics and outcomes.',
    count: 'meetings',
    search: 'Search meetings',
    searchPlaceholder: 'Search title, company, project, participant',
    filters: {
      company: 'Company',
      project: 'Project',
      type: 'Type',
      participant: 'Participant',
      status: 'Status',
      from: 'From',
      to: 'To',
    },
    columns: {
      meeting: 'Meeting',
      when: 'When',
      type: 'Type',
      status: 'Status',
      decisions: 'Decisions',
      tasks: 'Tasks',
      languages: 'Languages',
      duration: 'Duration',
    },
    emptyTitle: 'No meetings match',
    emptyBody: 'Nothing was captured in this workspace for these filters yet.',
    emptyAllTitle: 'No meetings in this workspace',
    emptyAllBody: 'A meeting becomes searchable once its transcript and analysis are ready.',
    rowCounts: 'outcomes',
    filteredNotice: 'Filters are in the address bar, so a filtered view can be shared or reloaded.',
  },
  meeting: {
    tabsIntro: 'Tabs are real routes: every view below has its own address.',
    actions: {
      play: 'Play recording',
      export: 'Export',
      share: 'Share',
      more: 'More',
    },
    playbackUnavailable:
      'Audio lives on the machine that recorded it. This build has no native bridge, so playback is shown as an interface contract, not a working player.',
    overview: {
      title: 'Overview',
      summary: 'Executive summary',
      summaryEmpty: 'No summary was produced for this meeting.',
      keyDecisions: 'Key decisions',
      actionItems: 'Action items',
      openQuestions: 'Open questions',
      participants: 'Participants',
      stats: 'At a glance',
      statsNote: 'Counts only. A meeting that produced nothing is a fact, not a chart.',
      words: 'words',
      speakers: 'speakers',
      speakingShare: 'Speaking share',
      topics: 'topics',
      confirmedOf: 'confirmed of',
      decisions: 'decisions',
      unmappedTitle: 'Speaker mapping is incomplete',
      unmappedBody:
        'Some lines are still labelled by diarization only, so they cannot be attributed to a person yet.',
    },
    topics: {
      title: 'Topics',
      intro: 'Sections in the order they occurred, with what came out of each one.',
      mapTitle: 'Topic map',
      emptyTitle: 'No topics were segmented',
      emptyBody: 'Topic segmentation runs after the transcript is prepared.',
      keywordHint: 'Keywords are taken from the transcript, not invented.',
      spoke: 'Spoke',
      coverage: 'Coverage',
      segmentsCovered: 'lines covered',
    },
    transcript: {
      title: 'Transcript',
      intro:
        'Every line is timestamped and clickable. Evidence elsewhere in the product points here.',
      search: 'Search in transcript',
      searchPlaceholder: 'Find words in this transcript',
      speaker: 'Speaker',
      topic: 'Topic',
      allSpeakers: 'All speakers',
      allTopics: 'All topics',
      resultsFor: 'Matching lines',
      noResultsTitle: 'Nothing in this transcript matches',
      noResultsBody: 'The search is literal and covers this meeting only.',
      emptyTitle: 'No transcript yet',
      emptyBody: 'The transcript appears once the captured audio has been aligned and transcribed.',
      unmapped: 'unmapped',
      mapSpeakers: 'Map speakers',
      mappedNotice: 'Mapping is stored per meeting and is not voice biometrics.',
      lineCount: 'lines',
      position: 'Position',
      jumpToTime: 'Jump to time',
      activeFilter: 'Filtered view',
      clearFilters: 'Clear transcript filters',
      highlightNote: 'This line is highlighted because a citation pointed at it.',
      emptyAfterFilter: 'No lines match this filter.',
    },
    decisions: {
      title: 'Decisions',
      intro: 'What was agreed, what is still provisional, and what was decided against.',
      emptyTitle: 'No decisions recorded',
      emptyBody: 'Not every meeting produces decisions. Nothing was invented for this one.',
      statusFilter: 'Status',
      followUps: 'Follow-up tasks',
      supersededNotice:
        'Superseded decisions stay visible with their replacement, because the history is the value.',
    },
    tasks: {
      title: 'Tasks',
      intro:
        'Commitments with an owner, a deadline where one was set, and the line they came from.',
      emptyTitle: 'No tasks from this meeting',
      emptyBody: 'Nothing was committed in this conversation.',
    },
    facts: {
      title: 'Facts',
      intro: 'Figures and constraints stated in the meeting, with the sentence each came from.',
      emptyTitle: 'No facts extracted',
      emptyBody: 'Facts appear when a stated figure, budget or constraint is captured.',
      categoryFilter: 'Category',
      confidenceNote:
        'The small bar is transcription confidence, not a claim that the number is true.',
    },
    questions: {
      title: 'Questions',
      intro: 'What was left open, and what answered it.',
      emptyTitle: 'No open questions',
      emptyBody: 'Every question raised in this meeting was answered in it.',
      statusFilter: 'Status',
    },
    ideas: {
      title: 'Ideas',
      intro: 'Suggestion and possibility, kept apart from commitments on purpose.',
      emptyTitle: 'No ideas recorded',
      emptyBody: 'Ideas are what was floated without being agreed to.',
    },
    processing: {
      title: 'Pipeline',
      notReady: 'This meeting is not ready yet',
      stepOf: 'Step',
      retry: 'Retry failed step',
      demoAdvance: 'Advance demo state',
      demoAdvanceHint:
        'Development-only: moves this meeting one step forward in the fixture pipeline. No transcription or analysis runs.',
      noPercentages:
        'Progress is reported as documented steps. This build does not measure percentages, so it does not show any.',
      failedNotice: 'Completed steps are kept; only the failed step needs to run again.',
    },
  },
  speakers: {
    dialogTitle: 'Map a speaker',
    dialogIntro:
      'Assign the diarization label to a person. Audio is not analysed for identity, and no voiceprint is stored.',
    label: 'Speaker label',
    person: 'Person in this workspace',
    choosePerson: 'Choose a person',
    confirm: 'Confirm mapping',
    cancel: 'Cancel',
    unmappedCount: 'labels still unmapped',
    mappedNotice: 'Mapping updates the lines carrying this label in this meeting only.',
    unavailable:
      'Speaker mapping needs the live adapter; in demo mode it updates in-memory state only.',
  },
  companies: {
    title: 'Companies',
    intro:
      'Each company holds its meetings, projects and the record of what was decided with them.',
    search: 'Search companies',
    emptyTitle: 'No companies yet',
    emptyBody: 'Companies group meetings, projects and the knowledge produced in them.',
    writeNote:
      'Companies are created through the workspace adapter. In demo mode a new company is held in this session’s memory; a live deployment writes it to the workspace database.',
    columns: {
      company: 'Company',
      projects: 'Projects',
      meetings: 'Meetings',
      openTasks: 'Open tasks',
      decisions: 'Decisions',
      lastMeeting: 'Last meeting',
    },
    detail: {
      meetings: 'Meetings',
      projects: 'Projects',
      decisions: 'Decisions',
      tasks: 'Tasks',
      knowledge: 'Knowledge',
      overview: 'Overview',
      activeProjects: 'Active projects',
      openTasks: 'Open tasks',
      team: 'Team involved',
    },
    intelligence: {
      title: 'Company record',
      note: 'Structured from the meeting fixtures in this workspace. No model was called to produce it.',
      derivedFrom: 'Derived from',
      derivedFromDemo: 'demo fixtures',
      derivedFromPipeline: 'the analysis pipeline',
      updated: 'Updated',
      emptySection: 'Nothing recorded in this section yet.',
      emptySectionBody:
        'These sections are part of the record shape and will fill as meetings are analyzed. Nothing is invented to occupy them.',
      emptySections: (count: number) =>
        `${count} ${count === 1 ? 'section has' : 'sections have'} nothing recorded yet`,
      more: (count: number) => `${count} more in this section`,
      entries: 'entries in this record',
      entryOne: '1 entry',
      entryOther: 'entries',
      sectionsNav: 'Jump to a section of the company record',
      objectionNote: 'Objections are kept because they predict friction, not to score anyone.',
    },
  },
  projects: {
    title: 'Projects',
    intro: 'Work split with a company, tracked through the meetings that move it.',
    search: 'Search projects',
    emptyTitle: 'No projects yet',
    emptyBody: 'A project groups the meetings that advance one piece of work.',
    detail: {
      overview: 'Overview',
      meetings: 'Meetings',
      decisions: 'Decisions',
      tasks: 'Tasks',
      knowledge: 'Knowledge',
    },
    status: { active: 'Active', paused: 'Paused', closed: 'Closed' },
    company: 'Company',
    writeNote:
      'Projects are created through the workspace adapter, and a project can be moved between companies only while no meeting of another company points at it.',
  },
  tasks: {
    title: 'Tasks',
    intro: 'Everything anyone committed to, across meetings, with the line it came from.',
    buckets: { all: 'All', mine: 'Mine', open: 'Open', overdue: 'Overdue', completed: 'Completed' },
    filters: {
      company: 'Company',
      project: 'Project',
      owner: 'Owner',
      status: 'Status',
      search: 'Search tasks',
    },
    searchPlaceholder: 'Search task text or owner',
    emptyTitle: 'No tasks in this view',
    emptyBody: 'Tasks come out of meetings, so this view is empty until one produces a commitment.',
    owner: 'Owner',
    deadline: 'Deadline',
    source: 'Source',
    unassigned: 'Unassigned',
    updateBlocked:
      'Task status is written by the live product’s data layer; demo state can be updated in this build only.',
    counts: 'tasks in view',
  },
  knowledge: {
    title: 'Knowledge',
    intro: 'Decisions, facts, topics, commitments and questions collected across the workspace.',
    kinds: 'Type',
    search: 'Search knowledge',
    searchPlaceholder: 'Search across everything captured',
    emptyTitle: 'Nothing matches',
    emptyBody: 'Knowledge is assembled from analysed meetings, not written by hand.',
    filters: {
      company: 'Company',
      project: 'Project',
      participant: 'Participant',
      from: 'From',
      to: 'To',
    },
    note: 'This is a filtered browse over typed records. There is no embedding search in this build, and no claim of one.',
    count: 'entries',
  },
  ask: {
    title: 'Ask AI',
    intro:
      'Questions answered from this workspace’s meetings, with every claim linked to the line it came from.',
    placeholder: 'Ask about a decision, an owner, a number, or what is still open',
    submit: 'Ask',
    clear: 'Clear',
    suggestions: 'Example questions',
    adapterLabel: 'Adapter',
    adapterDemo: 'fixture-backed demo adapter',
    adapterRag: 'retrieval pipeline',
    provenanceTitle: 'How this answer was produced',
    provenanceDemo:
      'Assembled deterministically from this workspace\u2019s records: keyword scoring picked the matches, then fixed templates wrote the sentences. No model generated this text, and no provider was contacted.',
    provenancePipeline:
      'Retrieved from the workspace records and assembled by the analysis pipeline; the citations below are the passages it read.',
    authoredDemo: 'hand-authored demo answer',
    retrievalDemo: 'ranked retrieval over the same records',
    deterministicBadge: 'deterministic synthesis',
    sources: 'Sources',
    noSources: 'This answer cites no record, so treat it as unproven.',
    emptyTitle: 'Nothing in this workspace matches that',
    emptyBody:
      'Ask about a company, a decision, an owner or a metric that appears in captured meetings.',
    disclaimer:
      'Demo adapter: answers are assembled from hand-authored fixtures and ranked retrieval over the same records. No language model is called, and no question leaves this machine.',
    asked: 'Asked',
    questionError: 'Type a question first.',
    noAnswer: 'There is no answer to show yet.',
  },
  newMeeting: {
    title: 'New meeting',
    intro: 'A meeting is captured on the recording machine, then prepared here.',
    steps: {
      company: 'Company',
      project: 'Project',
      title: 'Title',
      type: 'Type',
      participants: 'Participants',
      record: 'Start recording',
    },
    companyLabel: 'Company',
    companyHint:
      'Meetings can be workspace-level too; choosing a company scopes everything derived from it.',
    projectLabel: 'Project',
    projectHint: 'Optional. A project groups the meetings that advance one piece of work.',
    titleLabel: 'Title',
    titlePlaceholder: 'e.g. Foodera — Marketing Strategy',
    typeLabel: 'Meeting type',
    participantsLabel: 'Who is in the room',
    participantsHint:
      'Used for speaker mapping and for owner suggestions later. Nobody is looked up by voice.',
    recordTitle: 'Desktop recorder required',
    recordBody:
      'Recording is done by SUHBAT Desktop, which owns the microphone and system-audio capture. A browser page does not start a recording, and this build has no validated native bridge.',
    openDesktop: 'Open SUHBAT Desktop',
    createDraft: 'Create draft instead',
    startRecording: 'Start recording',
    recordingClaim: 'This page cannot confirm a recording. Open the desktop app to capture audio.',
    validation: 'Title must be 2–180 characters.',
    whenLabel: 'Planned for',
    durationLabel: 'Planned length (minutes)',
    notesLabel: 'What you want out of it',
    notesPlaceholder: 'The two numbers to settle, the decision that is blocking the next step…',
    draftBlocked:
      'The current data source has no draft write path, so nothing was created. The form is shown disabled rather than posting into a refusal.',
    demoDraftCreated:
      'A draft is a record in the workspace adapter — in demo mode that is this session’s memory. Nothing was recorded and no pipeline ran.',
    editTitle: 'Edit draft',
    editIntro:
      'A draft is the only meeting whose title, type and people can be corrected here. Once anything was captured, the records are the surface for corrections.',
    editSubmit: 'Save draft',
    deleteTitle: 'Delete this draft',
    deleteExplain:
      'Nothing has been recorded for it, so deleting removes only the placeholder. A meeting with a transcript or records cannot be deleted anywhere in this product.',
    deleteConfirm: 'Delete draft',
    notDraftTitle: 'This meeting is not a draft',
    notDraftBody:
      'It has been captured, so its identity is fixed: the transcript, decisions and tasks are where its content is corrected.',
    planned: 'Planned',
    notScheduled: 'no date set',
  },
  processing: {
    title: 'Processing',
    states: 'Pipeline state',
    queued: 'Queued',
    failed: 'Failed',
    demoTransition: 'Demo transition available',
    demoTransitionHint:
      'This moves the fixture one step forward so each state can be reviewed. It does not transcribe or analyse anything.',
  },
  settings: {
    title: 'Settings',
    intro:
      'Workspace configuration. Panels that would write to a service say what is not connected.',
    sections: {
      workspace: 'Workspace',
      members: 'Members',
      meetingTypes: 'Meeting types',
      vocabulary: 'Vocabulary',
      recording: 'Recording',
      ai: 'AI',
      integrations: 'Integrations',
    },
    workspace: {
      name: 'Workspace name',
      slug: 'Identifier',
      yourRole: 'Your role',
      members: 'Members',
      memberRole: 'Role',
      memberStatus: 'Status',
      inviteNote:
        'Member management runs through the live workspace data. In demo mode the roster is fixture data and cannot be edited.',
      readOnly: 'Read-only in this build',
    },
    meetingTypes: {
      builtIn: 'Built-in',
      custom: 'Custom',
      note: 'Types decide which prompts the analysis pipeline uses later. The list below is what the live workspace currently exposes.',
      add: 'Add meeting type',
      addBlocked:
        'Creating a meeting type writes to the workspace database. This build has no write path, so nothing was added.',
      key: 'Key',
      active: 'Active',
      inactive: 'Inactive',
    },
    vocabulary: {
      title: 'Vocabulary',
      intro:
        'Terms and pronunciations the transcription step should prefer. Scope decides where a term applies.',
      add: 'Add term',
      term: 'Term',
      context: 'Pronunciation / context',
      scope: 'Scope',
      scopes: { workspace: 'Workspace', company: 'Company', meeting: 'Meeting' },
      enabled: 'Enabled',
      disabled: 'Off',
      demoOnly: 'Demo fixtures only',
      note: 'Vocabulary is applied by the transcription step in the pipeline. Nothing here changes a transcript that already exists, and in demo mode nothing is persisted.',
    },
    recording: {
      title: 'Recording',
      intro:
        'What SUHBAT Desktop does on the recording machine. These are the values the desktop app was built against.',
      input: 'Preferred input',
      systemAudio: 'System audio',
      systemAudioOn: 'Captured as a second, separate source',
      retention: 'Local retention',
      screenContext: 'Screen context',
      format: 'Format',
      chunk: 'Recoverable chunk length',
      storage: 'Session folder',
      note: 'The recorder keeps microphone and system audio as logically separate sources on one canonical timeline. Pausing writes a silent gap rather than dropping time.',
      validation:
        'Native recorder validation on macOS has not been completed. These settings describe the implemented behaviour, not a verified capture.',
    },
    ai: {
      title: 'AI defaults',
      intro:
        'Language, summary style and analysis depth are workspace preferences. Provider credentials are not.',
      languages: 'Transcription languages',
      guessing: 'Speaker language guessing',
      summaryStyle: 'Summary style',
      styles: {
        executive_brief: 'Executive brief',
        detailed: 'Detailed',
        action_only: 'Action only',
      },
      depth: 'Analysis depth',
      depths: { essential: 'Essential', standard: 'Standard', thorough: 'Thorough' },
      provider: 'Provider',
      noProvider: 'No provider is configured in this build.',
      secretPolicy:
        'API keys are held by the server pipeline. This screen will not accept, display or store a key; a bring-your-own-key field would be a product decision first, not a settings input.',
      on: 'On',
      off: 'Off',
    },
    integrations: {
      title: 'Integrations',
      intro: 'Where meeting outcomes will eventually flow. Nothing is connected in this build.',
      connected: 'Connected',
      notConnected: 'Not connected',
      comingLater: 'Coming later',
      connect: 'Connect',
      connectBlocked:
        'Connecting an integration needs server-side credentials and a callback the pipeline owns. Not implemented, so nothing was connected.',
    },
  },
  /**
   * Every write flow's wording lives here, next to the rules the forms enforce, so a page never has to invent
   * a sentence about what saving means. The persistence caveat is not duplicated: it is read from
   * `capabilities.persistenceLabel`, which the adapter owns.
   */
  writes: {
    save: 'Save',
    create: 'Create',
    cancel: 'Cancel',
    back: 'Back',
    edit: 'Edit',
    archive: 'Archive',
    restore: 'Restore',
    delete: 'Delete',
    confirm: 'Confirm',
    archived: 'Archived',
    active: 'Active',
    showArchived: 'Show archived',
    hideArchived: 'Hide archived',
    archivedBadge: 'archived',
    closedBadge: 'closed',
    disabledBadge: 'disabled',
    readOnlyTitle: 'This screen is read-only on this data source',
    fieldRequired: 'required',
    optional: 'optional',
    nameHint: '2–120 characters. Names are unique per workspace so two records cannot be confused.',
    descriptionHint:
      'Up to 1000 characters. What this company is, in your own words — no fields to fill.',
    projectHint: 'A project may span several companies; linking one is optional.',
    duplicateHint: 'A duplicate name is refused rather than merged, so nothing silently combines.',
    archiveExplain:
      'Archiving keeps every meeting, decision and task that points here. The record leaves the default list and stays reachable by id, so history never loses its subject.',
    deleteExplain:
      'Deletion is offered only for a draft with no transcript and no records. Once anything was captured, the meeting is kept and corrected in place instead.',
    persistenceNote: 'Where this goes',
    createdCompany: 'Company created',
    newCompany: 'New company',
    editCompany: 'Edit company',
    newProject: 'New project',
    editProject: 'Edit project',
    editDraft: 'Edit draft',
    draftIntro:
      'A draft reserves a place for a conversation that has not happened. It does not start recording, schedule a job or notify anyone.',
    participantsHint:
      'Whoever is expected. The transcript later maps recorded voices onto these people by hand.',
    durationHint: 'Minutes. A planned length only; captured duration is recorded separately.',
    whenHint: 'Scheduled time for the conversation. Blank means today at 09:00 UTC.',
    notesHint: 'What you want to get out of it. Free text, never an insight.',
    meetingTypeHint:
      'Only active types can be chosen. Add one in settings if the list is missing something.',
  },
  export: {
    title: 'Export and print',
    intro:
      'These documents are built from the records this workspace already holds. Nothing is summarized again on the way out.',
    download: 'Download',
    print: 'Print',
    openPrint: 'Open print view',
    includeTranscript: 'Include the full transcript',
    transcriptIncluded: 'transcript included',
    transcriptOmitted: 'transcript omitted',
    formatHint:
      'Markdown for people, JSON for tools, CSV for a spreadsheet, plain text for anything else.',
    printNote: 'Print view: same records, one page per section, no navigation or actions.',
    generatedFrom: 'Generated from records stored in this workspace.',
    disclaimer: ' No model was called to produce this document.',
    noticesTitle: 'What this document is missing',
    transcriptOn: 'Hide the transcript',
    transcriptOff: 'Show the transcript',
    printLabels: {
      company: 'Company',
      project: 'Project',
      type: 'Type',
      when: 'When',
      outcome: 'Outcome',
      summary: 'Summary',
      summaryEmpty: 'No summary recorded for this meeting.',
      commitments: 'Commitments',
    },
  },
  transcript: {
    paging: 'Page',
    previous: 'Previous lines',
    next: 'Next lines',
    linesPerPage: 'Lines per page',
    jumped: 'Jumped to the cited line',
    filtered: 'filtered',
    ofTotal: 'of',
    lines: 'lines',
    noMatchesTitle: 'No transcript line matches those filters',
    noMatchesBody:
      'The transcript itself is unchanged; clear the filters to read the whole meeting.',
    clearFilters: 'Clear filters',
    showing: 'Showing',
  },
  searchPage: {
    recent: 'Recent in this workspace',
    recentHint:
      'The newest meetings and the soonest open work here. Nothing about your browsing is stored.',
    attention: 'Needs attention',
    attentionHint: 'Open work with a date, and meetings still waiting on speaker mapping.',
    noResultsTitle: 'Nothing matched',
    noResultsBody:
      'Search reads titles, names, decisions and tasks as text. There is no embedding index in this build, so a different wording may find it.',
    tooShortTitle: 'Type at least two characters',
    tooShortBody: 'Search is literal text matching over the records in this workspace.',
    results: 'results',
    result: 'result',
    focus: 'Search',
  },
  settingsWrites: {
    vocabularyTitle: 'Vocabulary',
    vocabularyIntro:
      'Words the transcription step should prefer. Nothing is transcribed in this build, so a term changes nothing until a provider exists — it is stored, not applied.',
    addTerm: 'Add term',
    term: 'Term',
    context: 'Context',
    contextHint: 'How it is used or pronounced. Optional, up to 200 characters.',
    scope: 'Applies to',
    scopeWorkspace: 'Whole workspace',
    scopeCompany: 'One company',
    scopeMeeting: 'One meeting',
    enabled: 'Enabled',
    disable: 'Disable',
    enable: 'Enable',
    edit: 'Edit term',
    delete: 'Delete term',
    deleteExplain:
      'Deleting a term only removes the term. Nothing that was already transcribed changes.',
    meetingTypesTitle: 'Meeting types',
    meetingTypesIntro:
      'The labels a draft can be filed under. Built-in types can be renamed and disabled but not removed, because meetings already reference them.',
    addType: 'Add meeting type',
    typeKey: 'Key',
    typeKeyHint:
      'Lowercase, letters, digits and underscores. This is what a future pipeline looks a type up by.',
    typeName: 'Display name',
    disableType: 'Disable',
    enableType: 'Enable',
    membersTitle: 'Members and invitations',
    membersIntro:
      'Who can see this workspace, and what they are holding. An invitation here is a roster entry: no mail leaves this build.',
    invite: 'Invite',
    inviteEmail: 'Email address',
    inviteRole: 'Role',
    invitedBadge: 'Invited',
    remove: 'Remove',
    removeExplain:
      'Removing a member takes their access only. Their meetings, decisions and tasks stay exactly where they are, which is why someone holding open work must be reassigned first.',
    roleOwner: 'owner',
    roleAdmin: 'admin',
    roleMember: 'member',
    openTasks: 'open tasks',
    meetingsCount: 'meetings',
    rosterNote:
      'Roles are displayed as the data reports them. Enforcement belongs to the backend RLS policies, which this build does not connect to.',
    workspaceTitle: 'Workspace',
    rename: 'Rename workspace',
    renameHint: 'The address and every existing link keep working; only the display name changes.',
  },
  a11y: {
    skip: 'Skip to main content',
    main: 'Main content',
    nav: 'Workspace navigation',
    loading: 'Loading',
    currentView: 'Current view',
  },
} as const;
